#!/bin/bash

clear
echo -e "#############################################"
echo -e "#  Libermod Installer by Hanif Widi Widodo  #"
echo -e "#############################################"
echo -e ""
sleep 1
echo -e "*Sebelum install libermod pastikan sudah terinstall libernet sebelumnya*"
echo -e ""
sleep 1
echo -e "- REMOVE LOGIN PAGE"
echo -e "- REMOVE SPEEDTEST PAGE"
echo -e "- CHANGE THEME COLOR"
echo -e "- CHANGE BACKGROUND IMAGE"
echo -e "- ADD BACKGROUND MUSIC"
echo -e "- FIX BENGONG (InshaAllah Aman)"
echo -e ""
sleep 3
echo -e "Harap tunggu, libermod segera di install..."
echo -e "#"
sleep 1
echo -e "##"
sleep 1
echo -e "###"
sleep 2
echo -e "Downloading file..."
{
opkg install unzip
wget -O /www/libernet.zip --no-check-certificate https://github.com/hanifwidi17/libermod/raw/main/libernet.zip
rm -r /www/libernet
} &> log-download.txt
echo -e "Extacting file..."
{
unzip /www/libernet.zip -d /www
} &> log-extract.txt
sleep 2
echo -e "Add Background Music..."
{
mkdir /www/libernet/music
} &> log-install.txt
sleep 2
echo -e "Mod & Change Theme Color..."
{
wget -O /www/libernet/music/music.mp3 --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/music.mp3
wget -O /www/libernet/system.php --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/system.php
wget -O /www/libernet/navbar.php --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/navbar.php
wget -O /www/libernet/index.php --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/index.php
wget -O /www/libernet/head.php --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/head.php
wget -O /www/libernet/footer.php --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/footer.php
wget -O /www/libernet/config.php --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/config.php
wget -O /www/libernet/about.php --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/about.php
wget -O /www/libernet/img/re.jpg --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/re.jpg
wget -O /www/libernet/assets/img/backgrounds/re.img --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/re.jpg
wget -O /www/libernet/lib/vendor/bootstrap/css/bootstrap.min.css --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/bootstrap.min.css
wget -O /root/libernet/bin/ping-loop.sh --no-check-certificate https://raw.githubusercontent.com/hanifwidi17/libermod/main/ping-loop.sh
} &> log-install.txt
rm /www/libernet.zip
rm install-libermod
echo -e ""
echo -e ""
echo -e "PROSES PEMASANGAN LIBERMOD SELESAI!"
echo -e "SILAHKAN CLEAR CACHE BROWSER ANDA SEBELUM MENGAKSES LIBERNET"
echo -e ""
